name: Unit Tests

on:
  push:
    branches:
      - master
      - release/*
      - feature/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        npm i
        npm run test
